### ISSUE TITLE
Tasks with asynchronous functions

### ISSUE THREAD

**Issue by leandromatos-hotmart** [jaclarke/cronosjs#11]
Every hour I need to run a routine that is asynchronous, it makes some requests to other methods, including external ones, and in case of error it returns an exception.

See an example.

```js
const expression = CronosExpression.parse('0 * * * *', {
  timezone: 'America/Sao_paulo'
})
const task = new CronosTask(expression)

task
  .on('run', async (timestamp) => {
    try {
      await someAsyncHandle()
    } catch (error) {
      throw error
    }
  })
  .start()
```

If `someAsyncHandle` returns an exception, an UnhandledPromiseRejectionWarning appears in the terminal.

Is there any way I can intercept the error inside `run`? Or is there an error method that intercepts any exceptions?

**Comment by jaclarke** [comment]
In your example you are intercepting the error that `someAsyncHandle` throws inside the `run` callback, however you are then re-throwing it causing the return of the `async (timestamp) => { ... }` callback function to become the unhandled rejected promise, hence the warning in the terminal.

Also since the `run` callback gets called at a later point in time (like a `setTimeout` callback), any try/catch block wrapping `task.on('run', ...)` will not catch that re-thrown error as that block will have returned before the callback is called. So to prevent the warning you either need to catch the error within the callback (like in your example, just without the re-throw) or add a global `unhandledRejection` listener on the node `process` (https://nodejs.org/api/process.html#process_event_unhandledrejection).

**Comment by leandromatos-hotmart** [comment]
After several attempts, using a catch in the asynchronous method, the code block works as expected.

```js
const expression = CronosExpression.parse('0 * * * *', {
  timezone: 'America/Sao_paulo'
})
const task = new CronosTask(expression)

task
  .on('run', async (timestamp) => {
    await someAsyncHandle().catch(error => {
      console.error(error)
    })
  })
  .start()
```

I just didn't understand the difference of trying to throw an exception directly from try/catch.
