### ISSUE TITLE
[Feature request] Possible to add job with 1 or more dates

### ISSUE THREAD

**Issue by Steve-Mcl** [jaclarke/cronosjs#4]
Hi again, 

I was wondering what the possibility of adding a feature.

Something like permitting a Job to be created from one or more dates.

Something like...

```
const  CronosTask = require("cronosjs").CronosTask;
const  CronosExpression = require("cronosjs").CronosExpression;
var aug30th = new Date("2020-08-30T12:00Z")
var myDates = [new Date("2020-09-01T12:00Z"), new Date("2020-10-01T12:00Z")]; 
var e1 = CronosExpression.parse( aug30th ); 
var e2 = CronosExpression.parse( myDates ); 

var t1 = new CronosTask(e1);
var t2 = new CronosTask(e2);
```

or

```
const  CronosTask = require("cronosjs").CronosTask;
var aug30th = new Date("2020-08-30T12:00Z");
var myDates = [new Date("2020-09-01T12:00Z"), new Date("2020-10-01T12:00Z")]; 
var t1 = new CronosTask(aug30th)
var t2 = new CronosTask(myDates)
```

Many thanks, Steve.

**Comment by jaclarke** [comment]
I don't think it would always be possible to create a valid cron expression from an array of dates, as each of the fields in a cron expression is independent. In your example it works since only the month is different, so something like `0 0 12 1 9,10 * 2020` matches just those dates, but if for example you gave the dates `['2020-09-01T12:00', '2020-10-01T13:00']` the closest cron expression would be something like `0 0 12,13 1 9,10 * 2020` but that would match the 4 combinations of `2020-09-01` and `2020-10-01` with `12:00` and `13:00`.

If you just want to create a task that triggers on each of a sequence of dates (or single date) that you provide instead of the sequence being defined by a cron expression, then that would be possible to implement.

**Comment by jaclarke** [comment]
## Implementation proposal
Have `CronosTask` accept any object implementing a `DateSequence` interface:
``` typescript
interface DateSequence {
    nextDate: (date: Date) => Date | null
}
```
with the requirement that the date returned by `nextDate` must be deterministic and be the next date in the sequence greater than the date provided to it, or `null` if there are no further dates in the sequence. This would allow the flexibility to create your own custom sequences, eg. every other day (the cron expression `0 0 */2 * *` is close, but can have irregular gaps at the end of the month depending on the number of days in the month), or a more complex sequence like sunrise and sunset times.

Also have an overload for the `CronosTask` constructor to take an array of dates or a date, and convert that internally to a class implementing the `DateSequence` interface as a convenience.

Any improvements / suggestions / comments?

**Comment by Steve-Mcl** [comment]
Hi, thanks for considering this.

I think that satisfies the current requirement I have + more.

Looking forward to your progress.

Thanks, Steve.
