### ISSUE TITLE
0 1/120 * * * * parses but interval is every 60 mins.

### ISSUE THREAD

**Issue by Steve-Mcl** [jaclarke/cronosjs#7]
Hi, I have this issue...

Expression `0 1/120 * * * *` evaluates to "Every 120 minutes, starting at 1 minutes past the hour" on several libs I have tested. [example](https://cronexpressiondescriptor.azurewebsites.net/?expression=0+1%2F120+*+*+*+*&locale=en)

  
`const e1 = CronosExpression.parse('0 1/120 * * * *') // doesnt seem to throw an error`
`const t1 = new CronosTask(e1) // creates task but it fires every hour`

Is it that `CronosExpression.parse()` should raise an error? or should 1/120 evaluate to 00:01, 02:01, 04:01 etc?

Demo [here](https://codepen.io/Steve-Mcl/pen/PoPPeLx?editors=0012)

**Comment by jaclarke** [comment]
As far as I can tell firing 'every hour at 1 minute past the hour' is technically the correct behaviour, since `1/120` is just a shortcut for `1-59/120`, meaning 'every 120th minute from 1 minute past the hour to 59 minutes past the hour' and the 'overflowing' minutes can't escape into the next hour, since cron is meant to be stateless. There doesn't seem to be any single well defined specification for how cron handles these edge cases (as least that I know of), but I was mostly cross-checking against [crontab.guru](https://crontab.guru/#1/120_*_*_*_*) when I was developing this library, and it seems to agree in this case.

Though it is technically a valid expression, it does seem that these cases where the step is greater than the range are probably not what the user intends and should be raised as an error. Since I don't want to break the existing behaviour, I'm thinking either having an optional `strict` option when parsing to opt in to throwing an error in this case, or creating a new `warnings` property on `CronosExpression` that would list problems like this that are syntactically valid, but are probably not what the user intended. I'm leaning more towards the second option, since it seems more backwards compatible, and could also include things like parts of expressions shadowing other parts, eg. `1-15,*`.

**Comment by Steve-Mcl** [comment]
Either option would result in a user being able to detect an issue.

Thanks for the consideration.

PS
some notes - might help you decide...
* Your [documentation](https://github.com/jaclarke/cronosjs#supported-expression-syntax) states `Allowed Fields             Minute             0-59` so I dont think a strict option is too bad a solution
* Quartz is strict by default (try `* 1/120 * * * ? *`  [here](https://www.freeformatter.com/cron-expression-generator-quartz.html) - you get "(Minutes) - Expression '120' is not a valid increment value. Accepted values are 0-59")

**Comment by jaclarke** [comment]
Closed by 2d19a9b
